DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS enrolled;

CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	FirstName TEXT NOT NULL,
	LastName TEXT NOT NULL,
	PrefName TEXT NOT NULL,
	Email TEXT NOT NULL,
	Passw TEXT NOT NULL,
	UserStatus TEXT NOT NULL,
	Course TEXT NOT NULL,
	Faculty TEXT NOT NULL
);

CREATE TABLE enrolled (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	Email TEXT NOT NULL,
	UnitOfStudy TEXT NOT NULL 
);